ReservationResort/Models/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace ReservationResort.Models
{
    public class ContactViewModel
    {

        [Required(ErrorMessage = "***Name is Required***")]
        public string Name { get; set; }

        [Required(ErrorMessage = "***Email is Required***")]
        [DataType(DataType.EmailAddress)]//shortcut to regex
        public string Email { get; set; }

        [Required(ErrorMessage = "***Required***")]
        public string Phone { get; set; }

        public string Subject { get; set; }

        [Required(ErrorMessage = "***Message is Required***")]
        [UIHint("MultilineText")]
        public string Message { get; set; }

    }
}

ReservationResort/Controllers/HomeController.cs
using System.Web.Mvc;
using System.Net.Mail;
using ReservationResort.Models;

namespace IdentitySample.Controllers
{
    public class HomeController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult FAQ()
        {
            return View();
        }

        public ActionResult Gallery()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        [HttpGet]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Contact(ContactViewModel contact)
        {
            //check the contact object for validity
            if (ModelState.IsValid)
            {
                //Create a body for the email (words)
                string body = string.Format($"Name: {contact.Name}<br />Email: {contact.Email}" +
                $"<br />Phone: {contact.Phone}<br /><br />{contact.Message}");

                //create and configure the Mail message (letter)
                MailMessage msg = new MailMessage("admin@comfortwalker.net",
                    contact.Email,//this is where we are sending to
                    contact.Phone, //subject of the message
                    body);

                //Configure the mail message object (evelope)
                msg.IsBodyHtml = true; //the body of the message is Html
                                       //msg.CC.Add("comfortwalker@outlook.com"); optional
                                       // msg.Bcc.Add("comfortwalker@outlook.com");optionl
                msg.Priority = MailPriority.High; //we want the email to end up in their mailbox

                //Create and configure the SMTP client (Mail person)
                SmtpClient client = new SmtpClient("mail.comfortwalker.net"); //Mail person
                client.Credentials = new System.Net.NetworkCredential("admin@comfortwalker.net", "Lovecomfort1@"); //stamp
                                                                                                                   //this part just attaches the username and password to the client so we can send the email
                                                                                                                   //client.Port = 8889; //the original is 25, but in case that port is being blocked
                                                                                                                   //you can change the port

                //send the email
                using (client)
                {

                    try
                    {
                        client.Send(msg); //sending the MailMessage object
                    }
                    catch
                    {
                        ViewBag.ErrorMessage = "There was an error sending your message, please email comfortwalker@outlook.com";
                        return View();
                    }

                }//using
                 //send the user to the Contact Confirmation view
                 //pass the contact object with it 

                return View("ContactConfirmation", contact);

            }//if
            else
            {
                return View(); //the model isn't valid, return to form
            }//else

        }

    }
}

ReservationResort/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReservationResort.Data.EF;
using Microsoft.AspNet.Identity;//adding for current user ID

namespace ReservationResort.Controllers
{
    [Authorize]
    public class ReservationsController : Controller
    {
        private FinalProjectEntities db = new FinalProjectEntities();

        // GET: Reservations
        public ActionResult Index()
        {
            //var reservations = db.Reservations.Include(r => r.Customer).Include(r => r.ResortLocation);

            if (User.IsInRole("Admin"))
            {
                List<ReservationResort.Data.EF.Reservation> reservations = db.Reservations.Include(r => r.Customer).Include(r => r.ResortLocation).ToList();
                return View(reservations);
            }
           else if(User.IsInRole("employee"))
            {
                var currentUserID = User.Identity.GetUserId();
                var ReservationsEmployeeLoc =
                    (from R in db.Reservations
                     join RL in db.ResortLocations on R.ResortLocationID equals RL.ResortLocationID
                     join EL in db.EmpLocations on RL.ResortLocationID equals EL.ResortLocationID
                     where EL.UserID == currentUserID
                     select R).ToList();

                return View(ReservationsEmployeeLoc);
                    
            }
            else
            {
                //Who the user is
                var currentUserID = User.Identity.GetUserId();

                //creating list of only this user Reservation items
                List<ReservationResort.Data.EF.Reservation> reservations =
                    db.Reservations.Where(x => x.CustomerID == currentUserID)
                    .Include(r => r.Customer).Include(r => r.ResortLocation)
                    .ToList();

                return View(reservations);
                    
            }
            //return View(reservations.ToList());
        }

        //Creating the Reservations
        public ActionResult customerReservation(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //create a new Reservation
            ReservationResort.Data.EF.Reservation Reservation = new Data.EF.Reservation();
            Reservation.ResortLocationID = (int)id;
            Reservation.ReservationDate = DateTime.Now;
            Reservation.CustomerID = User.Identity.GetUserId();

            db.Reservations.Add(Reservation);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        //Updating the Record with the return data

        public ActionResult Return(int id)
        {
            var item = db.Reservations.Find(id);
            item.ReservationDate = DateTime.Now;

            //Save and Update
            db.Entry(item).State = EntityState.Modified;
            db.SaveChanges();

            var currentUserId = User.Identity.GetUserId();
            //Creating a list of Only this User's Reservation items
            List<ReservationResort.Data.EF.Reservation> reservations =
                db.Reservations.Where(x => x.CustomerID == currentUserId)
                .Include(r => r.Customer).Include(r => r.ResortLocation)
                .ToList();

            return View("Index", reservations);

        }

        // GET: Reservations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // GET: Reservations/Create
        public ActionResult Create()
        {
            var currentUser = User.Identity.GetUserId();
            
                ViewBag.CustomerID = new SelectList(db.Customers.Where(x => x.ID == currentUser), "ID", "FirstName");
                ViewBag.ResortLocationID = new SelectList(db.ResortLocations, "ResortLocationID", "ResortName");
                     
            return View();
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReservationID,ResortLocationID,CustomerID,ReservationDate")] Reservation reservation)
        {
           

            //This is going to be the reservation Limit for the Current Location
            var RL = (from rl in db.ResortLocations
                      where rl.ResortLocationID == reservation.ResortLocationID
                      select rl.ReservationLimit).FirstOrDefault();

            //This list is all the Reservation at that location
            var reservationAtLocation = (from res in db.Reservations
                                         where res.ResortLocationID ==
                                         reservation.ResortLocationID
                                         select res).ToList();

            //This will get all reservation on the this location on this date
            var countOnDate = reservationAtLocation.Where(x => x.ReservationDate == reservation.ReservationDate).Count();

            //var nbrOfRes = reservationAtLocation.Where(x => x.ReservationDate == reservation.ReservationDate);
            //var number = nbrOfRes.Count();

            if (RL > countOnDate)
            {
                reservation.CustomerID = User.Identity.GetUserId();

                if (ModelState.IsValid)
                {
                    

                    db.Reservations.Add(reservation);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.CustomerID = new SelectList(db.Customers, "ID", "FirstName", reservation.CustomerID);
                ViewBag.ResortLocationID = new SelectList(db.ResortLocations, "ResortLocationID", "ResortName", reservation.ResortLocationID);
                return View(reservation);
            }
            else
            {
                ViewBag.CustomerID = new SelectList(db.Customers, "ID", "FirstName", reservation.CustomerID);
                ViewBag.ResortLocationID = new SelectList(db.ResortLocations, "ResortLocationID", "ResortName", reservation.ResortLocationID);
                ViewBag.LocationFullError = "Sorry, This location is full for this date. Please select another location or another date";
                return View(reservation);
            }
            
        }
     

        // GET: Reservations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerID = new SelectList(db.Customers, "ID", "FirstName", reservation.CustomerID);
            ViewBag.ResortLocationID = new SelectList(db.ResortLocations, "ResortLocationID", "ResortName", reservation.ResortLocationID);
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReservationID,ResortLocationID,CustomerID,ReservationDate")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reservation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerID = new SelectList(db.Customers, "ID", "FirstName", reservation.CustomerID);
            ViewBag.ResortLocationID = new SelectList(db.ResortLocations, "ResortLocationID", "ResortName", reservation.ResortLocationID);
            return View(reservation);
        }

        // GET: Reservations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reservation reservation = db.Reservations.Find(id);
            db.Reservations.Remove(reservation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ReservationResort/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<section id="about">

    <div class="container">
        <div class="row">

            <div class="col-lg-5 col-md-6">
                <div class="about-img">
                    <img src="img/about-img.jpg" alt="">
                </div>
            </div>

            <div class="col-lg-7 col-md-6">
                <div class="about-content">
                    <h2>About Us</h2>
                    <h3>Odio sed id eos et laboriosam consequatur eos earum soluta.</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    <p>Aut dolor id. Sint aliquam consequatur ex ex labore. Et quis qui dolor nulla dolores neque. Aspernatur consectetur omnis numquam quaerat. Sed fugiat nisi. Officiis veniam molestiae. Et vel ut quidem alias veritatis repudiandae ut fugit. Est ut eligendi aspernatur nulla voluptates veniam iusto vel quisquam. Fugit ut maxime incidunt accusantium totam repellendus eum error. Et repudiandae eum iste qui et ut ab alias.</p>
                    <ul>
                        <li><i class="ion-android-checkmark-circle"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
                        <li><i class="ion-android-checkmark-circle"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>
                        <li><i class="ion-android-checkmark-circle"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla pariatur.</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

</section><!-- #about -->

ReservationResort/Views/Home/Contact.cshtml
@model ReservationResort.Models.ContactViewModel

@{
    ViewBag.Title = "Contact";
}


@section Contact{
    
    
    
 @using (Html.BeginForm("Contact", "Home", FormMethod.Post, new { @class = "contactForm" }))
 {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="contact-mf">
                    <div id="contact" class="box-shadow-full">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="title-box-2">
                                    <h5 class="title-left">
                                        Send Message Us
                                    </h5>
                                </div>
                                <div>
                                    @*<form action="" method="post" role="form" class="contactForm">*@
                                    @*<div id="sendmessage">Your message has been sent. Thank you!</div>
                                        <div id="errormessage"></div>*@
                                    <div class="row">
                                        <div class="col-md-12 mb-3">
                                            <div class="form-group">
                                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @placeholder = "Name" } })
                                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-12 mb-3">
                                            <div class="form-group">
                                                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email" } })
                                                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-12 mb-3">
                                            <div class="form-group">
                                                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control", @placeholder = "Phone" } })
                                                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-12 mb-3">
                                            <div class="form-group">

                                                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control", @placeholder = "Subject" } })
                                                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-12 mb-3">
                                            <div class="form-group">
                                                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control", @placeholder = "Message" } })
                                                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <input type="submit" value="Send Message" class="button button-a button-big button-rouded" />

                                        </div>
                                    </div>
                                    @*</form>*@
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="title-box-2 pt-4 pt-md-0">
                                    <h5 class="title-left">
                                        Get in Touch
                                    </h5>
                                </div>
                                <div class="more-info">
                                    <p class="lead">
                                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis dolorum dolorem soluta quidem
                                        expedita aperiam aliquid at.
                                        Totam magni ipsum suscipit amet? Autem nemo esse laboriosam ratione nobis
                                        mollitia inventore?
                                    </p>
                                    <ul class="list-ico">
                                        <li><span class="ion-ios-location"></span> 329 WASHINGTON ST BOSTON, MA 02108</li>
                                        <li><span class="ion-ios-telephone"></span> (617) 557-0089</li>
                                        <li><span class="ion-email"></span> contact@example.com</li>
                                    </ul>
                                </div>
                                <div class="socials">
                                    <ul>
                                        <li><a href=""><span class="ico-circle"><i class="ion-social-facebook"></i></span></a></li>
                                        <li><a href=""><span class="ico-circle"><i class="ion-social-instagram"></i></span></a></li>
                                        <li><a href=""><span class="ico-circle"><i class="ion-social-twitter"></i></span></a></li>
                                        <li><a href=""><span class="ico-circle"><i class="ion-social-pinterest"></i></span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

 }
    
    
 }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ReservationResort/Views/Home/ContactConfirmation.cshtml
@model ReservationResort.Models.ContactViewModel

@{
    ViewBag.Title = "Contact Confirmation";
}

<div class="row">
    <div class="col-sm-offset-3 col-md-4">
        <h2 class="title text-center">Contact Confirmation</h2>
        <h3 class="title text-center">
            Thank you for Contacting Us!<br />
            We will get back to you as soon as possible
        </h3>
    </div>
</div>

ReservationResort/Views/Home/FAQ.cshtml
@{
    ViewBag.Title = "FAQ";
}

<section id="faq">
    <div class="container">
        <header class="section-header">
            <h3>Frequently Asked Questions</h3>
            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque</p>
        </header>

        <ul id="faq-list" class="wow fadeInUp">
            <li>
                <a data-toggle="collapse" class="collapsed" href="#faq1">Non consectetur a erat nam at lectus urna duis? <i class="ion-android-remove"></i></a>
                <div id="faq1" class="collapse" data-parent="#faq-list">
                    <p>
                        Feugiat pretium nibh ipsum consequat. Tempus iaculis urna id volutpat lacus laoreet non curabitur gravida. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non.
                    </p>
                </div>
            </li>

            <li>
                <a data-toggle="collapse" href="#faq2" class="collapsed">Feugiat scelerisque varius morbi enim nunc faucibus a pellentesque? <i class="ion-android-remove"></i></a>
                <div id="faq2" class="collapse" data-parent="#faq-list">
                    <p>
                        Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Id interdum velit laoreet id donec ultrices. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Est pellentesque elit ullamcorper dignissim. Mauris ultrices eros in cursus turpis massa tincidunt dui.
                    </p>
                </div>
            </li>

            <li>
                <a data-toggle="collapse" href="#faq3" class="collapsed">Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi? <i class="ion-android-remove"></i></a>
                <div id="faq3" class="collapse" data-parent="#faq-list">
                    <p>
                        Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Faucibus pulvinar elementum integer enim. Sem nulla pharetra diam sit amet nisl suscipit. Rutrum tellus pellentesque eu tincidunt. Lectus urna duis convallis convallis tellus. Urna molestie at elementum eu facilisis sed odio morbi quis
                    </p>
                </div>
            </li>

            <li>
                <a data-toggle="collapse" href="#faq4" class="collapsed">Ac odio tempor orci dapibus. Aliquam eleifend mi in nulla? <i class="ion-android-remove"></i></a>
                <div id="faq4" class="collapse" data-parent="#faq-list">
                    <p>
                        Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Id interdum velit laoreet id donec ultrices. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Est pellentesque elit ullamcorper dignissim. Mauris ultrices eros in cursus turpis massa tincidunt dui.
                    </p>
                </div>
            </li>

            <li>
                <a data-toggle="collapse" href="#faq5" class="collapsed">Tempus quam pellentesque nec nam aliquam sem et tortor consequat? <i class="ion-android-remove"></i></a>
                <div id="faq5" class="collapse" data-parent="#faq-list">
                    <p>
                        Molestie a iaculis at erat pellentesque adipiscing commodo. Dignissim suspendisse in est ante in. Nunc vel risus commodo viverra maecenas accumsan. Sit amet nisl suscipit adipiscing bibendum est. Purus gravida quis blandit turpis cursus in
                    </p>
                </div>
            </li>

            <li>
                <a data-toggle="collapse" href="#faq6" class="collapsed">Tortor vitae purus faucibus ornare. Varius vel pharetra vel turpis nunc eget lorem dolor? <i class="ion-android-remove"></i></a>
                <div id="faq6" class="collapse" data-parent="#faq-list">
                    <p>
                        Laoreet sit amet cursus sit amet dictum sit amet justo. Mauris vitae ultricies leo integer malesuada nunc vel. Tincidunt eget nullam non nisi est sit amet. Turpis nunc eget lorem dolor sed. Ut venenatis tellus in metus vulputate eu scelerisque. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Nibh tellus molestie nunc non blandit massa enim nec.
                    </p>
                </div>
            </li>

        </ul>

    </div>
</section><!-- #faq -->

ReservationResort/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<section id="intro" class="clearfix">
    <div class="container d-flex h-100">
        <div class="row justify-content-center align-self-center">
            <div class="col-md-6 intro-info order-md-first order-last">
                <h2>Creek's<br>Quest <span>Resorts Bookings</span></h2>
                <div>
                    <a href="@Url.Action("Index", "Reservations")" class="btn btn-get-started scrollto">Get Started</a>
                </div>
            </div>

            <div class="col-md-6 intro-img order-md-last order-first">
                <img src="img/intro-img.svg" alt="" class="img-fluid">
            </div>
        </div>

    </div>
</section><!-- #intro -->