ReservationResort/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReservationResort.Data.EF;
using Microsoft.AspNet.Identity;

namespace ReservationResort.Controllers
{
    [Authorize]
    public class CustomersController : Controller
    {
        private FinalProjectEntities db = new FinalProjectEntities();

        // GET: Customers
        public ActionResult Index()
        {
            if (User.IsInRole("Admin") || User.IsInRole("employee"))
            {
                return View(db.Customers.ToList());
            }
            else if(User.IsInRole("customer"))
            {
                var c = User.Identity.GetUserId();
                return Redirect("Customers/Details/" + c);
            }
            return View(db.Customers.ToList());

        }

        // GET: Customers/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // GET: Customers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
        [Bind(Include = "ID,FirstName,LastName,PhotoURL,SpecialNotes,IsActive,DateAdded,Phone,Email")]
        Customer customer, HttpPostedFileBase customerPhoto)
        {
            customer.ID = User.Identity.GetUserId();
            customer.IsActive = true;

            if (ModelState.IsValid)
            {

                #region File Upload
                //checking to see if there was a file upload, if not, default to the noimage.png
                string file = "noImage.png";

                if (customerPhoto != null)
                {
                    //getting the name 
                    file = customerPhoto.FileName;

                    //getting the extension
                    string ext = file.Substring(file.LastIndexOf('.'));

                    //checking extensions against a list of 'good' extensions
                    string[] goodExts = { ".jpg", "jpeg", ".png", ".gif" };

                    //seeing if this file is a photo
                    if (goodExts.Contains(ext))
                    {
                        //this is a valid photo
                        //checking the file size to make sure it's not too Large
                        if (customerPhoto.ContentLength <= 10000000)//10mb
                        {
                            //incase this is the second time around and they have a file that fits
                            Session["SizeError"] = null;

                            //creating a unique name for each customer photo
                            file = customer.LastName + DateTime.Now.Year + ext;

                            //save file to server
                            customerPhoto.SaveAs((Server.MapPath("~/Content/Images/" + file)));

                        }//if less than 10 Million bytes
                        else
                        {
                            //the photo was too big
                            Session["SizeError"] = "Your photo was to big, try again";
                            return RedirectToAction("Edit", customer.ID);

                        }
                    }//if contains extension


                    //Updating the PhotoURL Property of new student
                    //in the database
                    customer.PhotoURL = file;


                }//end if customerPhoto not null

                #endregion


                //in case this is the second time around and they have a file that fits
                Session["SizeError"] = null;


                db.Customers.Add(customer);
                db.SaveChanges();
                return RedirectToAction("Index");

            }

            return View(customer);
        }

        // GET: Customers/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName,PhotoURL,SpecialNotes,IsActive,DateAdded,Phone,Email")] Customer customer,
             HttpPostedFileBase customerPhoto)
        {
            if (ModelState.IsValid)
            {

                #region File Upload
                //checking to see if there was a file upload, if not, default to the noimage.png
                string file = "noImage.png";

                if (customerPhoto != null)
                {
                    //getting the name 
                    file = customerPhoto.FileName;

                    //getting the extension
                    string ext = file.Substring(file.LastIndexOf('.'));

                    //checking extensions against a list of 'good' extensions
                    string[] goodExts = { ".jpg", "jpeg", ".png", ".gif" };

                    //seeing if this file is a photo
                    if (goodExts.Contains(ext))
                    {
                        //this is a valid photo
                        //checking the file size to make sure it's not too Large
                        if (customerPhoto.ContentLength <= 10000000)//10mb
                        {
                            //incase this is the second time around and they have a file that fits
                            Session["SizeError"] = null;

                            //creating a unique name for each customer photo
                            file = customer.LastName + DateTime.Now.Year + ext;

                            //save file to server
                            customerPhoto.SaveAs((Server.MapPath("~/Content/Images/" + file)));

                        }//if less than 10 Million bytes
                        else
                        {
                            //the photo was too big
                            Session["SizeError"] = "Your photo was to big, try again";
                            return RedirectToAction("Edit", customer.ID);

                        }
                    }//if contains extension


                    //Updating the PhotoURL Property of new student
                    //in the database
                    customer.PhotoURL = file;


                }//end if customerPhoto not null

                #endregion


                //in case this is the second time around and they have a file that fits
                Session["SizeError"] = null;

                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Customer customer = db.Customers.Find(id);
            AspNetUser user = db.AspNetUsers.Find(id);
            db.AspNetUsers.Remove(user);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ReservationResort/Controllers/ResortLocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ReservationResort.Data.EF;

namespace ReservationResort.Controllers
{
    public class ResortLocationsController : Controller
    {
        private FinalProjectEntities db = new FinalProjectEntities();

        // GET: ResortLocations
        public ActionResult Index()
        {
            return View(db.ResortLocations.ToList());
        }

        // GET: ResortLocations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResortLocation resortLocation = db.ResortLocations.Find(id);
            if (resortLocation == null)
            {
                return HttpNotFound();
            }
            return View(resortLocation);
        }

        // GET: ResortLocations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ResortLocations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ResortLocationID,ResortName,Address,City,State,ZipCode,ReservationLimit")] ResortLocation resortLocation)
        {
            if (ModelState.IsValid)
            {
                db.ResortLocations.Add(resortLocation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(resortLocation);
        }

        // GET: ResortLocations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResortLocation resortLocation = db.ResortLocations.Find(id);
            if (resortLocation == null)
            {
                return HttpNotFound();
            }
            return View(resortLocation);
        }

        // POST: ResortLocations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ResortLocationID,ResortName,Address,City,State,ZipCode,ReservationLimit")] ResortLocation resortLocation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(resortLocation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(resortLocation);
        }

        // GET: ResortLocations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResortLocation resortLocation = db.ResortLocations.Find(id);
            if (resortLocation == null)
            {
                return HttpNotFound();
            }
            return View(resortLocation);
        }

        // POST: ResortLocations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ResortLocation resortLocation = db.ResortLocations.Find(id);
            db.ResortLocations.Remove(resortLocation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ReservationResort/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Creek's Quest Resort</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicons -->
    <link href="img/favicon.png" rel="icon">
    <link href="img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,500,600,700,700i|Montserrat:300,400,500,600,700" rel="stylesheet">

    <!-- Bootstrap CSS File -->
    <link href="~/Content/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

    <!--Added bootstrap-->
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>


    <!-- Libraries CSS Files -->
    <link href="~/Content/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/Content/lib/ionicons/css/ionicons.min.css" rel="stylesheet">
    <link href="~/Content/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/Content/lib/lightbox/css/lightbox.min.css" rel="stylesheet">

    <!-- Main Stylesheet File -->
    <link href="~/Content/css/style.css" rel="stylesheet">

    <!--Datatable.net CSS-->
    <link href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" rel="stylesheet" />

    <!--Jqueryui Datepicker-->
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">



    <!--Customer Css-->
    <link href="~/Content/CustomeStyles.css" rel="stylesheet" />
    <!-- =======================================================
      Theme Name: Rapid
      Theme URL: https://bootstrapmade.com/rapid-multipurpose-bootstrap-business-template/
      Author: BootstrapMade.com
      License: https://bootstrapmade.com/license/
    ======================================================= -->
</head>
<body>
    <!--==========================
    Header
    ============================-->
    <header id="header">

        <div id="topbar">
            <div class="container">
                <div class="social-links">

                    <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                    <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                    <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
                    <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>

                </div>
            </div>
        </div>

        <div class="container">

            <div class="logo float-left">
                <!-- Uncomment below if you prefer to use an image logo -->
                <h1 class="text-light"><a href="#intro" class="scrollto"><span>Creek's Quest</span></a></h1>
                <!-- <a href="#header" class="scrollto"><img src="img/logo.png" alt="" class="img-fluid"></a> -->
            </div>

            <nav class="main-nav float-right d-none d-lg-block">
                <ul>
                    <li class="active"><a href="@Url.Action("Index", "Home")">Home</a></li>
                    <li><a href="@Url.Action("Contact", "Home")">Contact</a></li>
                    <li><a href="@Url.Action("Index", "ResortLocations")">Resorts</a></li>
                    <li class="drop-down">
                        <a href="">Reservations</a>
                        <ul>
                            @if (Request.IsAuthenticated && User.IsInRole("Admin") || User.IsInRole("employee"))
                            {
                                <li><a href="@Url.Action("Index", "Customers")">Users</a></li>

                            }
                            else if (Request.IsAuthenticated)
                            {
                                <li><a href="@Url.Action("Index", "Customers")">My Account</a></li>
                            }
                            <li class="drop-down">
                                <a href="#">About</a>
                                <ul>
                                    <li><a href="@Url.Action("FAQ", "Home")">FAQ</a></li>
                                    <li><a href="@Url.Action("About", "Home")">About Us</a></li>
                                </ul>

                            </li>
                            @if (Request.IsAuthenticated && User.IsInRole("customer"))
                            {
                                <li><a href="@Url.Action("Index", "Reservations")">My Reservations</a></li>
                            }
                            else if (Request.IsAuthenticated)
                            {
                                <li><a href="@Url.Action("Index", "Reservations")">Reservations</a></li>
                            }                           
                        </ul>
                    </li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                    @Html.Partial("_LoginPartial")
                </ul>
            </nav><!-- .main-nav -->

        </div>
    </header><!-- #header -->
    <!--==========================
      Intro Section
    ============================-->


    <main id="main">

        @RenderBody()

        <!--==========================
          About Us Section
        ============================-->
        <!--==========================
          Services Section
        ============================-->
        <!--==========================
          Why Us Section
        ============================-->
        <!--Removed Why Us-->
        <!--==========================
          Call To Action Section
        ============================-->
        <!--Removed call to Action-->
        <!--==========================
          Features Section
        ============================-->
        <!--Removed Features-->
        <!--==========================
          Portfolio Section
        ============================-->
        <!--Removed Portfolio -->
        <!--==========================
          Clients Section
        ============================-->
        <!--Removed Testamonial-->
        <!--==========================
          Team Section
        ============================-->
        <!--Removed Team-->
        <!--==========================
          Clients Section
        ============================-->
        <!--Removed Our Clients section-->
        <!--==========================
          Pricing Section
        ============================-->
        <!--Removed Pricing Section-->
        <!--==========================
          Frequently Asked Questions Section
        ============================-->

    </main>

    <!--==========================
      Footer
    ============================-->
    <footer id="footer" class="section-bg">
        <!--Contact was removeed from here-->

        @RenderSection("Contact", false)

        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong>Rapid</strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!--
                  All the links in the footer should remain intact.
                  You can delete the links only if you purchased the pro version.
                  Licensing information: https://bootstrapmade.com/license/
                  Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Rapid
                -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>
    </footer><!-- #footer -->

    <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
    <!-- Uncomment below i you want to use a preloader -->
    <!-- <div id="preloader"></div> -->
    <!-- JavaScript Libraries -->
    <script src="~/Content/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/lib/jquery/jquery.min.js"></script>
    <script src="~/Content/lib/jquery/jquery-migrate.min.js"></script>
    <script src="~/Content/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/Content/lib/easing/easing.min.js"></script>
    <script src="~/Content/lib/mobile-nav/mobile-nav.js"></script>
    <script src="~/Content/lib/wow/wow.min.js"></script>
    <script src="~/Content/lib/waypoints/waypoints.min.js"></script>
    <script src="~/Content/lib/counterup/counterup.min.js"></script>
    <script src="~/Content/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/Content/lib/isotope/isotope.pkgd.min.js"></script>
    <script src="~/Content/lib/lightbox/js/lightbox.min.js"></script>
    <!-- Contact Form JavaScript File -->
    @*<script src="contactform/contactform.js"></script>*@

    <!-- Template Main Javascript File -->
    <script src="~/Content/js/main.js"></script>

    <!--Javascript for Datatables.net (function calls will be in the views, passed to the RenderSection(scripts))-->
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <!--Javascrpt for datepicker-->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    @RenderSection("scripts", required: false)

    <!--Scripts for datepicker-->
    <script>
        $(function () {
            $("#datepicker").datepicker({
                changeMonth: true,
                changeYear: true
            });
        });
    </script>

</body>
</html>

ReservationResort/Views/Shared/_OriginalLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>

                    @if (Request.IsAuthenticated && User.IsInRole("Admin")) {
                        <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                        <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>